### ISSUE TITLE
Call module in model

### ISSUE THREAD

**Issue by eluhr** [eluhr/yii2-shop-module#16]
The approach of calling a module property callable in a model is far from ideal. We may need a better solution to make this future proof.

Change (https://github.com/eluhr/yii2-shop-module/commit/6c31af83805066bef603bfe3424fb729c46e0eab) was made to prevent a dependency to a whole new module.

CC: @handcode

**Comment by handcode** [comment]
any "working" solution that is not 'hardcode external package-dependency to get an image url' is better, so https://github.com/eluhr/yii2-shop-module/commit/6c31af83805066bef603bfe3424fb729c46e0eab seems to be ok for me ;-)
